config/routes.rb
Rails.application.routes.draw do
  # get 'movies/index'
  # get 'movies/show'
  # post 'movies/create'
  # get 'movies/new'
  # put 'movies/update'
  # patch 'movies/update'
  # get 'movies/edit'
  # delete 'movies/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "movies", to: "movies#index"
  post "movies", to: "movies#create"
  get "movies/new", to: "movies#new", as: 'new_movie'
  get "movies/:id/edit", to: "movies#edit", as: "edit_movie"
  get "movies/:id",to: "movies#show", as: 'movie'
  put "movies/:id",to: "movies#update"
  patch "movies/:id",to: "movies#update"
  delete "movies/:id",to: "movies#destroy"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movie33 = Movie.all
  end

  def show
    @movie1 = Movie.find(params[:id])
  end

  def create
    # render json: params[:movie]
    @movie = Movie.new(save_data)
    @movie.save

    redirect_to @movie
  end

  private def save_data
    params.require(:movie).permit(:title,:runtime,:genre,:release_date)

  end

  def new
    @movie = Movie.new
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(save_data)

    redirect_to @movie
  end

  def edit
    @movie = Movie.find(params[:id])
    # render json: @movie
  end

  def destroy
    render json: params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BollyFilm1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= form_with model: @movie, local:true do |form|%>
    <p>
        <%= form.label :title%>
        <%=form.text_field :title%>
    </p>
        <p>
        <%= form.label :runtime%>
        <%=form.text_field :runtime%>
    </p>
        <p>
        <%= form.label :genre%>
        <%=form.text_field :genre%>
    </p>
        <p>
        <%= form.label :release_date%>
        <%=form.text_field :release_date%>
    </p>
    <%= form.submit "Update Movie"%>
<%end%>

app/views/movies/index.html.erb
<h1>Movies</h1>
<%link_to "New Movie", new_movie_path%>
<%= @movie33.each do |movie| %>
    <div>
        <%=movie.inspect%>
        <%=link_to "Edit Movie ",edit_movie_path(movie)%>
        <%=link_to "Delete Movie", movie_path(movie),method: :delete, data: {confirm:"are you sure?"}%>
        
    </div>

<%end%>

app/views/movies/new.html.erb
<h1>New Movie</h1>
<%= form_with model: @movie, local: true do |form|%>

    <p>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </p>

    <p>
        <%= form.label :genra%>
        <%= form.text_field :genra%>
    </p>

    <p>
        <%= form.label :runtime%>
        <%= form.text_field :runtime, type: "number"%>
    </p>

    <p>
        <%= form.label :release_date%>
        <%= form.text_field :release_date, type:"date"%>
    </p>


    <%= form.submit "Save Movie"%>


<%end%>

app/views/movies/show.html.erb
<h1>Show Movies</h1>

<%= @movie1.inspect%>
<%=link_to "Movies", movies_path%>